- name: Install and Configure PostgreSQL
  hosts: dbservers
  become: yes
  tasks:
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Start Postgresql
      ansible.builtin.service: #Ensure it is running
        name: postgresql
        state: started
        enabled: yes

    - name: Create Database
      community.postgresql.postgresql_db:
        name: flaskdb
        login_user: postgres

    - name: Create User
      community.postgresql.postgresql_user:
        db: flaskdb
        name: flaskuser
        password: 1234
        login_user: postgres

    - name: Ensure Data Directory is Persisted
      ansible.builtin.file:
        path: /var/lib/postgresql/data
        state: directory
        owner: postgres
        group: postgres
        mode: 0700 #DONT UNDERSTAND


