- name: Set up Server
  hosts: webservers
  become: true
  tasks:  
    - name: Install Flask
      pip:
        name:
        - Flask
        - gunicorn
        - psycopg2-binary
        - python-dotenv

    - name: Upload Flask App
      copy:
        src: ./app.py
        dest: /opt/flask_app/
        mode: 0755

    - name: Copy gunicorn systemd file
      template:
        src: ./ansible_quickstart/systemd
        dest: /etc/systemd/system/gunicorn_flask.service

    - name: Reload systemd
      shell: systemctl daemon-reload

    - name: Start systemd
      systemd:
        name: gunicorn_flask
        enabled: yes
        state: started

 