- name: Set Up Flask Web Server
  hosts: webservers
  become: yes
  vars:
    instance_name: "{{ ansible_hostname }}"
    db_name: "postgres"
    db_user: "postgres"
    db_password: "password"
    db_host: "{{ hostvars['db1']['ansible_host'] }}"
    db_port: "5432"
    app_port: "5000"
  tasks:
    - name: Install Required Packages
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-wsgi-py3
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Python Dependencies
      ansible.builtin.pip:
        requirements: /home/ubuntu/requirements.txt

    - name: Copy Flask App
      ansible.builtin.copy:
        src: /local/path/to/app/
        dest: /var/www/flask-app/
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Set Environment Variables
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      loop:
        - "INSTANCE_NAME={{ instance_name }}"
        - "DB_NAME={{ db_name }}"
        - "DB_USER={{ db_user }}"
        - "DB_PASSWORD={{ db_password }}"
        - "DB_HOST={{ db_host }}"
        - "DB_PORT={{ db_port }}"
        - "APP_PORT={{ app_port }}"

    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
